buildscript {
	ext {
		cleanArchitectureVersion = '4.7.2'
		springBootVersion = '3.5.16'
		jacocoVersion = '0.8.13'
		lombokVersion = '1.18.48'
		mapstructVersion = '1.5.3.Final'
		resilience4jVersion = '2.3.0'
		springdocVersion = '2.8.17'
		blockHoundVersion = '1.0.17.RELEASE'
	}
}

plugins {
	id 'co.com.bancolombia.cleanArchitecture' version "${cleanArchitectureVersion}"
	id 'org.springframework.boot' version "${springBootVersion}" apply false
	id 'jacoco'
	id 'base'
}

apply from: './main.gradle'
