server:
  port: 8085
spring:
  application:
    name: franchise
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/franchise?sslmode=require
    username: postgres
    password: Maddy-2026
  sql:
    init:
      mode: never
  logging:
    level:
      org.springframework.web.reactive.function.server: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true