server:
  port: 8085
spring:
  application:
    name: franchise
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  sql:
    init:
      mode: never
  logging:
    level:
      org.springframework.web.reactive.function.server: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true