server:
  port: 8085
spring:
  application:
    name: franchise
  r2dbc:
    url: r2dbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.fcpkybgszpjagzojyyzm
    password: Maddy-2026
  sql:
    init:
      mode: never
  logging:
    level:
      org.springframework.web.reactive.function.server: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true