variable "name" {
  type        = string
  description = "Prefix for resource names, usually <project>-<environment>"
}

variable "private_subnet_ids" {
  type        = list(string)
  description = "Private subnets where the database lives (at least two availability zones)"
}

variable "security_group_id" {
  type        = string
  description = "Security group that only allows PostgreSQL from the API tasks"
}

variable "engine_version" {
  type        = string
  description = "PostgreSQL major version"
  default     = "16"
}

variable "instance_class" {
  type        = string
  description = "RDS instance class"
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  type        = number
  description = "Storage in GiB"
  default     = 20
}

variable "database_name" {
  type        = string
  description = "Name of the application database"
  default     = "franchise"
}

variable "master_username" {
  type        = string
  description = "Master user, its password is generated by RDS and stored in Secrets Manager"
  default     = "franchise_admin"
}

variable "multi_az" {
  type        = bool
  description = "Create a standby replica in another availability zone"
  default     = false
}

variable "backup_retention_days" {
  type        = number
  description = "Days of automated backups, 0 disables them"
  default     = 0
}

variable "skip_final_snapshot" {
  type        = bool
  description = "Skip the final snapshot when the database is destroyed"
  default     = true
}

variable "deletion_protection" {
  type        = bool
  description = "Prevent the database from being destroyed"
  default     = false
}
